### ISSUE TITLE
Hanging on Ionic Serve

### ISSUE THREAD

**Issue by Benyeled817** [auth0/auth0-ionic2#1]
I cloned the repo, ran npm install and when I run ionic serve it completes the "HTML copied to www/build" step and then just hangs. Looking at the Activity Monitor I can see that Ionic is spiking up to 99.9% of my CPU.

FYI - I was able to use the code in this repo to get auth0 running in my app, I just couldn't actually run the demo itself. I don't need it, I was just creating this issue to give you a heads up in case someone else encounters this.

**Comment by Benyeled817** [comment]
[This forum post](https://forum.ionicframework.com/t/auth0-ionic-sample-app-causes-digest-cycle-to-keep-running/40619) may resolve it for others.

**Comment by chenkie** [comment]
Thanks for the heads up! I'll take a closer look when I get a chance.
