### ISSUE TITLE
App crashes on "Sign Up"

### ISSUE THREAD

**Issue by DanailMinchev** [auth0/auth0-ionic2#11]
Hi,

I am using `Android 5.0.2`. When I go to Lock Widget -> Sign Up - the app crashes after successful sign up.

I partly solved it by adding `inappbrowser` plugin:
`ionic plugin add cordova-plugin-inappbrowser`

But, now after sign up the `inappbrowser` is not being closed and stays on `about:blank` page - it needs to be closed automatically.

I tried the latest lock as well: `https://cdn.auth0.com/js/lock-9.2.min.js` - does not work.

**Comment by DanailMinchev** [comment]
Found similar issue here: https://github.com/auth0/auth0-ionic/issues/17

**Comment by chenkie** [comment]
Just updated Ionic 2 to beta 7. Can you try the update and let me know if you still get the issue? :)

**Comment by DanailMinchev** [comment]
Hi,

The issues still exists as described - no changes in behaviour.

1. Original project + android platform - the app crashes
2. With `cordova-plugin-inappbrowser` plugin - the `about:blank` displayed
3. I have added `sso: false` and it works, but I think this is not a solution - I may need `sso` eventually

**Comment by clickstefan** [comment]
have the same issue,
Cordova CLI: 6.2.0
Ionic Framework Version: 2.0.0-beta.7
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
OS: Distributor ID:     Ubuntu Description:     Ubuntu 14.04.4 LTS 
Node Version: v4.4.7

**Comment by chenkie** [comment]
Can you try the latest and let me know if this issue still exists? It uses Lock v10

**Comment by jayhuang75** [comment]
Same here!
Cordova CLI: 6.1.1
Ionic Framework Version: 2.0.0-beta.9
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.18
Node Version: v5.8.0

**Comment by chenkie** [comment]
Can you try the latest here? https://github.com/auth0-samples/auth0-ionic2-samples/tree/master/01-Login

If the problem still occurs, please open a new issue there :)

**Comment by jayhuang75** [comment]
Once I updated, Its back on the track! :)
Thanks @chenkie

**Comment by nicosabena** [comment]
The blank window after signup was fixed in [Lock v10.18](https://github.com/auth0/lock/releases/tag/v10.18.0).
