### ISSUE TITLE
Doesn't work with ionic beta.10

### ISSUE THREAD

**Issue by chrishawn** [auth0/auth0-ionic2#13]
changes to the use of ionicBootstrap seem to cause problems.. as well as provider issues... fixed most of them, but now all i get is it hanging on load with a pending request to badge.png... no idea where to go from here.

assuming it should be as simple as
`ionicBootstrap(MyApp, [
    HTTP_PROVIDERS,
    AUTH_PROVIDERS,
    AuthService
]);`
when all is said and done, but i think all the betas and rc not gelling well at the moment

**Comment by jayhuang75** [comment]
Any update about this?

**Comment by nadreal** [comment]
Have same problem.
Is there  some easier way to do authentication, just from mysql database ?

**Comment by chenkie** [comment]
Can you try the latest update and let me know if it works?

**Comment by chrishawn** [comment]
Yes that seems to work, quite a bit of retooling on my side to adjust to the changes..
also these warnings kept coming up
```
npm WARN angular2-jwt@0.1.18 requires a peer of @angular/core@^2.0.0-rc.4 but none was installed.
npm WARN angular2-jwt@0.1.18 requires a peer of @angular/http@^2.0.0-rc.4 but none was installed.
```
but i just changed package.json dependencies line to
 ```
 "dependencies": {
    "@angular/common": "^2.0.0-rc.4",
    "@angular/compiler": "^2.0.0-rc.4",
    "@angular/core": "^2.0.0-rc.4",
    "@angular/http": "^2.0.0-rc.4",
    "@angular/platform-browser": "^2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.4",
    "angular2-jwt": "^0.1.16",
    "es6-shim": "^0.35.0",
    "ionic-angular": "2.0.0-beta.10",
    "ionic-native": "^1.3.2",
    "ionicons": "3.0.0",
    "quill": "^0.20.1",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12"
  },
```
and redid a `npm install` and all was good
