### ISSUE TITLE
Back button doesn't work after login (ex fb)

### ISSUE THREAD

**Issue by clickstefan** [auth0/auth0-ionic2#14]
How to reproduce:

- go to app
- login via fb
- try back button (even after switching apps and navigating through the tabs)

If I forcefully close it and open it again, it will work, and the user will be logged in.

**Comment by chenkie** [comment]
Can you check whether this still happens in the latest update? https://github.com/auth0-samples/auth0-ionic2-samples/tree/master/01-Login

Please open another issue there if the problem persists :)
