### ISSUE TITLE
Undefined alert after ~20sec when social login popup is open

### ISSUE THREAD

**Issue by clickstefan** [auth0/auth0-ionic2#15]
How to reproduce:

- start app
- try fb login (when not signed in the mobile browser)
- wait 20sec

This raises the problem of not having enough time to type the credentials and causes the user to start all over again.

**Comment by chenkie** [comment]
Can you try the latest and let me know if this issue still exists?

**Comment by hughred22** [comment]
Same issue in V9. Trying the latest, but there is lots of issues on the new docs. Like in NOT in mobile size screen, after login, I can not click anything...

**Comment by chenkie** [comment]
Can you try the latest update: https://github.com/auth0-samples/auth0-ionic2-samples/tree/master/01-Login

Open a new issue there if the problem persists :)
