### ISSUE TITLE
How to Unit Test this?

### ISSUE THREAD

**Issue by nottinhill** [auth0/auth0-ionic2#16]
Hi I want to test this. But getting:

    ORIGINAL EXCEPTION: ReferenceError: Auth0Lock is not defined

Is there a possibility to mock Auth0Lock which is _declared_ in my service as by best practice?

**Comment by chenkie** [comment]
Hey there, is this still an issue? We're moving everything over to here: https://github.com/auth0-samples/auth0-ionic2-samples/tree/master/01-Login

Please open a new issue if there are still problems :)
