### ISSUE TITLE
Lock 10 problem for my app and how to solve it?!?! 

### ISSUE THREAD

**Issue by hughred22** [auth0/auth0-ionic2#19]
Just follow this guide and there are some issues: 
This new tutorial makes my app not working correctly any more. 

First, the login() function do not return as a promise. Which my app is waiting for the resolve to setRoot to a Home page from login page (where the Auth0 are called). It is not gonna work on this new tutorial.

Second, I can not dynamic set the connections with this.lock.show({options}). The lock.show ignores all the options and I can not set the display of lock dynamically anymore since V10. My app is, before popup the Lock, I let users pick what kind of user they are , then show related SSO login depend on the value they choose. For users are business, I show Email/PW login ONLY. For users pick YouTube Creator, I will need google SSO with YouTube scope. But since the lock is initialized during the login constructor, I can not update the login option based on user choices. 

With this new tutorial using V10 Lock, how would I dynamically set the allowedConnections?

Thanks!!

**Comment by chenkie** [comment]
New sample: https://github.com/auth0-samples/auth0-ionic2-samples/tree/master/01-Login
