### ISSUE TITLE
When screen size is bigger than mobile, I lost all control after login...

### ISSUE THREAD

**Issue by hughred22** [auth0/auth0-ionic2#20]
More issue. After following the tutorial, when I logged in on mobile, (screen size smaller than iPad), it seems to work. But when in desktop mode, after I logged in, I can not click anything. Look like something site on top of my view that does not got clean... Please help!

**Comment by hughred22** [comment]
![screen shot 2016-07-22 at 6 20 29 pm](https://cloud.githubusercontent.com/assets/2126155/17074918/09165588-5039-11e6-84cf-8e593601d807.png)

Here is the div with z-index 9998 sit right on top of everything that cover my home-page cotent!

**Comment by chenkie** [comment]
This is likely an issue with how you've got your pages set up and not an issue with Lock or Auth0 itself. Can you share your code?

**Comment by hughred22** [comment]
Thanks for the reply. You are right for that one. My logout button is on a popup, and I did not call the dismiss function before setRoot (call it after), and I think that is causing the invisible div on top of my view. Beside this, I do have 2 other questions I will need answer b/c of the change of tutorial. I will open an new ticket.
