### ISSUE TITLE
Lost margin-top: 56px when successfully lock in redirect... 

### ISSUE THREAD

**Issue by hughred22** [auth0/auth0-ionic2#21]
So there is also a display problem. When I successfully locked in, I set rootPage to Home page. But the scroll-content does not have margin-top: 56px  added in the style to make sure my content will not attached under the header. When I go to other view and come back, the margin-top will get added. So it is only happen after redirect from Auth0 lock. Do you know why? 

So since I can not listen to a promise with my login call in Lock V10. Now my strategy (not sure if it is right), is to use this code in my login.ts constructor: 

     `this.auth.lock.on('authenticated', authResult => {
        console.log("Authenticated Successfully!");
        his.nav.setRoot(HomePage);
      });`

So the login button only do lock.show(). That is the only different I have from your Tutorial codes as your tutorial login and content are all in a same page.

**Comment by chrishawn** [comment]
I am seeing this as well and it is very annoying
