### ISSUE TITLE
Example using my own login screen

### ISSUE THREAD

**Issue by chrishawn** [auth0/auth0-ionic2#22]
i would love an example of how to use this with my own username and password fields if possible? Not using the pop up lock screen

**Comment by chenkie** [comment]
Thanks for the suggestion :) We're working on improving our docs to show different scenarios and custom login is one of those. In the meantime, have a look at our Angular 2 custom login doc. Chances are you'll be able to make it work with Ionic 2 from that: https://auth0.com/docs/quickstart/spa/angular2/02-custom-login

**Comment by chrishawn** [comment]
is it true that custom login only works with a callback url though? because that is not possible in a mobile app that i know of.

**Comment by chrishawn** [comment]
ok answering my own question it is not true... and i did get this working from the samples without lock.js

my rewrite of auth.login

```
public login(email, password) {
       this.auth0.login({
            connection: 'Prod-Username-PW-Auth',
            email: email,
            password: password,
            scope: 'openid email offline_access picture',
            device: 'mobile',
        }, (err, authResult) => {
            if (err){
                console.error(err);
            }else{
                console.log("authenticated");
                this.local.set('id_token', authResult.idToken);

                // Fetch profile information
                this.auth0.getProfile(authResult.idToken, (error, profile) => {
                    if (error) {
                        console.error(error);
                        // Handle error
                        alert(error);
                        return;
                    }
                    console.log(profile);
                    profile.user_metadata = profile.user_metadata || {};
                    this.local.set('profile', JSON.stringify(profile));
                    this.user = profile;
                    this.user.login=true;
                    this._user.next(this.user);
                });

                this.local.set('refresh_token', authResult.refreshToken);
                this.zoneImpl.run(() => {
                    this.user = authResult.profile;
                });
                // Schedule a token refresh
                this.scheduleRefresh();
            }
        });
}
```

**Comment by matiasmoya** [comment]
Hi @chrishawn! can you share your auth.service.ts file? I have some doubts related with this line in the constructor for ionic `var result = this.auth0.parseHash(window.location.hash);`, I think we wont get that location hash modified by auth0 in mobile devices
