### ISSUE TITLE
Relogin problems

### ISSUE THREAD

**Issue by chrishawn** [auth0/auth0-ionic2#23]
using the Lock 10 version... when i log in a second time and am presented with the "Last time you logged in with" screen, this does not seem to work.. pops open to another screen showing the old lock? maybe from the auth0 site? which never authenticates.

**Comment by chenkie** [comment]
Can you check if you're still getting this in the latest updated? We're moving everything over to here so please open a new issue if there are still problems :) https://github.com/auth0-samples/auth0-ionic2-samples/tree/master/01-Login
