### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'split' of null on "startupTokenRefresh()"

### ISSUE THREAD

**Issue by lauravl** [auth0/auth0-ionic2#25]
Hello, I'm trying to Implement Refresh Tokens on an Ionic 2 application using Auth 0 guide.
But I receive the following error when try to access the application after I close it (without logging out):
`Error: Uncaught (in promise): TypeError: Cannot read property 'split' of null`
Therefore, I believe the error happens in startupTokenRefresh().

ionic info output:
Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.32
Ionic App Lib Version: 2.0.0-beta.19
OS:
Node Version: v4.4.5

**Comment by chenkie** [comment]
Fixed in the latest update: https://github.com/auth0-samples/auth0-ionic2-samples/tree/master/01-Login
