### ISSUE TITLE
not working with ionic2 beta 11

### ISSUE THREAD

**Issue by shalaby** [auth0/auth0-ionic2#26]
I am using Ionic2 beta 11, Angular2 rc 4.
but I am getting this error:
`
node_modules/angular2-jwt/angular2-jwt.ts:1
import { provide, Injectable } from '@angular/core';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
`

**Comment by oliviercherrier** [comment]
This version encountered dependencies error with Ionic2 beta11. Try using  https://github.com/oliviercherrier/auth0-ionic2

Pull request in progress.

**Comment by cyberbobjr** [comment]
Hi, 
Same problem here : error with angular2-jwt although with the fork of oliviercherrier :(

Thanks for your help
regards

**Comment by chenkie** [comment]
New sample for rc0: https://github.com/auth0-samples/auth0-ionic2-samples/tree/master/01-Login
