### ISSUE TITLE
CustomURLScheme adding Issue

### ISSUE THREAD

**Issue by mibzman** [auth0/auth0-ionic2#31]
This may be related to the ionic-cli issue [#2305](https://github.com/driftyco/ionic-cli/issues/2305)

In the Auth0 Getting started is says to run:
```
ionic cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME={YOUR_PACKAGE_ID} --variable ANDROID_SCHEME={YOUR_PACKAGE_ID} --variable ANDROID_HOST=hungerperks.auth0.com --variable ANDROID_PATHPREFIX=/cordova/{YOUR_PACKAGE_ID}/callback
```

Since `ionic cordova` is currently broken I ran
```
cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME={YOUR_PACKAGE_ID} --variable ANDROID_SCHEME={YOUR_PACKAGE_ID} --variable ANDROID_HOST=hungerperks.auth0.com --variable ANDROID_PATHPREFIX=/cordova/{YOUR_PACKAGE_ID}/callback
```
and

```
ionic plugin add cordova-plugin-customurlscheme --variable URL_SCHEME={YOUR_PACKAGE_ID} --variable ANDROID_SCHEME={YOUR_PACKAGE_ID} --variable ANDROID_HOST=hungerperks.auth0.com --variable ANDROID_PATHPREFIX=/cordova/{YOUR_PACKAGE_ID}/callback
```

both resulted in an `unknown url scheme` error from chrome after the 'login' or 'signup' button is pushed.

**Comment by mibzman** [comment]
I can confirm that this example project works, but I am still having this issue in the app I am trying to integrate into

**Comment by chenkie** [comment]
Hi @mibzman. This repo is actually deprecated. Are you looking for [this one](https://github.com/auth0-samples/auth0-ionic2-samples)?

**Comment by mibzman** [comment]
apparently!  Thanks!
