### ISSUE TITLE
Duplicated viewport meta tag

### ISSUE THREAD

**Issue by nunoarruda** [auth0/auth0-ionic2#4]
Heads up: Ionic's index.html already has the viewport meta tag, no need to add it again.
<img width="814" alt="screen shot 2016-03-29 at 10 42 38" src="https://cloud.githubusercontent.com/assets/1189149/14096394/04ff39d6-f59b-11e5-8fcb-ede199198c00.png">

**Comment by chenkie** [comment]
Thank you!
