### ISSUE TITLE
cannot get it to run, keeps on throwing errors

### ISSUE THREAD

**Issue by ashishtilara** [auth0/auth0-ionic2#7]
I am getting following error, also with new ionic cli, it can't find gulpfile.js, so `ionic serve` doesn't work straightaway.

```
app/theme/app.ios.scss
Error: File to import not found or unreadable: ionic.ios
       Parent style sheet: stdin
        on line 20 of stdin
>> @import 'ionic.ios';
   ^
```

Is it possible to get this example in non-ts version, I mean in ES2015.

cheers

**Comment by chenkie** [comment]
I was having issues installing a fresh Ionic project from the ionic cli yesterday, so I wonder if it might be related. I'll take a look :)

**Comment by chenkie** [comment]
I pushed an update which should resolve this. Try cloning again and let me know if it works :)

**Comment by ashishtilara** [comment]
Thanks @chenkie, It works now, but login only worked once, then it started failing with following error
![screen shot 2016-04-14 at 10 12 31 pm](https://cloud.githubusercontent.com/assets/1509613/14527541/1502f3ae-028e-11e6-8ae7-114fe3846ff6.png)

Steps to reproduce: 
1. Click on profile tab
2. click on login
3. I have google login enabled so I click on Login with google on Auth0Lock screen
4. I cancel/close login screen
5. start getting error from then onwards...
6. refresh screen, and Ping button goes tiny, and things are broken :cry:

**Comment by chenkie** [comment]
It's likely that you've got `null` values in local storage. Can you check that and remove them?

**Comment by ashishtilara** [comment]
I tried removing those values, but still same. I assume its a bug in angular2-jwt lib, because either that or Lock should not be setting those variables in local storage, correct?
